export declare const userRoot: string;
export declare const runtimeDir: string;
export declare const PRELOAD_PATH: string;
export declare const GUEST_PRELOAD_PATH: string;
export declare const TWEAKS_DIR: string;
export declare const LOG_DIR: string;
export declare const LOG_FILE: string;
export declare const CONFIG_FILE: string;
export declare const CODEX_CONFIG_FILE: string;
export declare const INSTALLER_STATE_FILE: string;
export declare const UPDATE_MODE_FILE: string;
export declare const SELF_UPDATE_STATE_FILE: string;
export declare const SIGNED_CODEX_BACKUP: string;
export declare const CODEX_PLUSPLUS_VERSION = "1.1.5";
export declare const CODEX_PLUSPLUS_REPO = "LightHaru/chatgpt-layer";
export declare const TWEAK_STORE_INDEX_URL: string;
export declare const CODEX_WINDOW_SERVICES_KEY = "__codexpp_window_services__";
export type RuntimeLog = (level: "info" | "warn" | "error", ...args: unknown[]) => void;
export declare function log(level: "info" | "warn" | "error", ...args: unknown[]): void;
